docs: update Portuguese translation
t3-oss/create-t3-app pull request #1128
Opened 2023-01-27 01:51 UTC by gilhrpenner

Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Created the missing pages for the deploy section as well as reordered  the content of a few pages that had changes.

2023-01-31 22:22 UTC, c-ehrlich commented
@claudiofreitas
@minsk-dev
@Sn0wye
@victoriaquasar

2023-01-31 23:17 UTC, victoriaquasar commented on www/src/pages/pt/deployment/docker.md
> +> - _Usando imagens baseada em Alpine 3.17 [pode causar problemas no Prisma](https://github.com/t3-oss/create-t3-app/issues/975). Setting `engineType = "binary"` corrige esse problema no Alpine 3.17,
```suggestion
> - _Usando imagens baseadas em Alpine 3.17 [pode causar problemas no Prisma](https://github.com/t3-oss/create-t3-app/issues/975). Realizando a configuração: `engineType = "binary"` corrige esse problema no Alpine 3.17, [mas apresenta um custo de performance adicional](https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#the-query-engine-at-runtime)._
```

2023-01-31 23:17 UTC, victoriaquasar commented on www/src/pages/pt/deployment/netlify.md
> +Netlify é um provedor de implantação alternativo em uma linha semelhante ao Vercel. Veja [`ajcwebdev/ct3a-netlify`](https://github.com/ajcwebdev/ct3a-netlify) para um repositório de exemplo baseado n
```suggestion
Netlify é um provedor de computação em nuvem remota com suporte a frameworks modernos de desenvolvimento, semelhante ao Vercel. Veja [`ajcwebdev/ct3a-netlify`](https://github.com/ajcwebdev/ct3a-netlify) para um repositório de exemplo baseado neste documento.
```

2023-01-31 23:17 UTC, victoriaquasar commented on www/src/pages/pt/deployment/netlify.md
> +A sabedoria convencional diz que o Vercel tem suporte superior ao Next.js porque o Vercel desenvolve o Next.js. Eles têm um interesse em garantir que a plataforma seja otimizada para o melhor desempe
```suggestion
Comumente, a plataforma Vercel tem um suporte mais refinado ao Next.js porque o a mesma desenvolve o framework. Eles têm um interesse em garantir que a plataforma seja otimizada para o melhor desempenho e DX com o Next.js. Para a maioria dos casos de uso, isso será verdade e não fará sentido usar outras alternativas.
```

2023-01-31 23:17 UTC, victoriaquasar commented on www/src/pages/pt/deployment/netlify.md
> +Também existe um sentimento comum de que muitos recursos do Next.js são suportados apenas no Vercel. Embora seja verdade que os novos recursos do Next.js serão testados e suportados no Vercel no mome
```suggestion
Também sabe-se que muitos recursos do Next.js são suportados apenas no Vercel. Embora seja verdade que os novos recursos do Next.js serão testados e suportados no Vercel no momento do lançamento por padrão, também é o caso de que outros provedores, como o Netlify, [implementarão e lançarão rapidamente suporte](https://www.netlify.com/blog/deploy-nextjs-13/) para [recursos Next.js estáveis](https://docs.netlify.com/integrations/frameworks/next-js/overview/).
```

2023-02-02 03:22 UTC, victoriaquasar commented
> Closes #
> 
> ## ✅ Checklist
> * [x]  I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
> * [x]  The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
> * [x]  I performed a functional test on my final commit
> 
> ## Changelog
> Created the missing pages for the deploy section as well as reordered the content of a few pages that had changes.

Which issue does it close?

2023-02-02 04:59 UTC, victoriaquasar commented on www/src/pages/pt/usage/next-auth.md
> +  // NOTE: `session` wont have a loading state since it's already prefetched on the server
Traduzir comentário (não faz parte do código)

2023-02-05 22:42 UTC, gilhrpenner commented
> 

I went over the existing issues and didn't see any for pt-BR translation. When I have some time tomorrow I can go over the guidelines and open an issue.

2023-02-07 00:25 UTC, Sn0wye commented
A página da Netlify já foi criada, favor verificar.
Netlify page has already been created, please check.

2023-02-07 22:44 UTC, c-ehrlich submitted a review, later dismissed
Thanks for the contribution and for taking the time to update so much of the docs.

We just merged a different translation for the Netlify page. Could you please resolve the merge conflict (feel free to modify the existing Netlify page as little or as much as you want, and then we'll have the other translators review it.

2023-02-08 04:13 UTC, gilhrpenner commented
@c-ehrlich @Sn0wye fixed the merge conflict with the existing Netlify page.

2023-02-08 09:25 UTC, Sn0wye commented on www/src/pages/pt/deployment/index.astro
> +  description: "Aprenda como dar deploy na sua aplicação T3 para produção.",
```suggestion
  description: "Aprenda como fazer deploy para produção na sua aplicação T3.",
```

2023-02-08 09:35 UTC, Sn0wye requested changes
Just a few changes here and there, but looking great!

2023-02-08 09:35 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.md
> +Alguns frameworks e ferramentas de construção, como o Next.js, sugerem que você armazene segredos em um arquivo `.env.local` e commita arquivos `.env` em seu projeto. Isso não é recomendado, pois pod
```suggestion
Alguns frameworks e outras ferramentas, como o Next.js, sugerem que você armazene variáveis em um arquivo `.env.local` e faça commit de arquivos `.env` em seu projeto. Isso não é recomendado, pois poderia facilitar o acidente de  incluir variáveis ambiente secretas em seu histórico do git. Em vez disso, recomendamos que você armazene essas variáveis no arquivo `.env`, mantenha o arquivo `.env` em seu `.gitignore` e faça commit somente de arquivos `.env.example` em seu projeto.
```

2023-02-08 09:35 UTC, Sn0wye commented on www/src/pages/pt/usage/next-auth.md
> +Às vezes, você poderá querer solicitar a sessão no servidor. Para fazer isso, faça uma requisição usando o helper `getServerAuthSession` que `create-t3-app` fornece e passe-a para o cliente usando `g
```suggestion
Às vezes, você poderá querer solicitar a sessão no servidor. Para fazer isso, faça uma requisição usando o utilitário `getServerAuthSession` que `create-t3-app` fornece e passe-a para o cliente usando `getServerSideProps`:
```

2023-02-08 09:35 UTC, Sn0wye commented on www/src/pages/pt/usage/trpc.md
> +## Files
```suggestion
## Arquivos
```

2023-02-08 17:49 UTC, gilhrpenner commented
> Just a few changes here and there, but looking great!

Thanks 😄 
Been living outside of Brazil for more than 10 years, sometimes it's harder to translate a few tech terms I haven't used in the past lol

2023-02-11 02:38 UTC, Sn0wye approved these changes
All good! 🎉

2023-02-11 09:35 UTC, juliusmarminge approved these changes

2023-02-11 09:37 UTC, juliusmarminge commented
Stale**

2023-02-11 09:37 UTC, merged