docs: remove `unstable`
t3-oss/create-t3-app pull request #1165
Opened 2023-02-05 07:46 UTC by NekoChanTaiwan

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

remove `unstable` in other languages.

2023-02-05 13:55 UTC, c-ehrlich commented
Wow the notifications are working :)

2023-02-05 13:59 UTC, AmadeusTwi commented
While this is a good edit, I also noticed that the bulletpoint was expanded with some new text in English docs.
I'm not sure if we should delete "unstable" in this PR in multiple languages or encourage just plain updating the page itself in these languages.

2023-02-05 14:08 UTC, Sn0wye requested changes
That's it.

2023-02-05 14:08 UTC, Sn0wye commented on www/src/pages/pt/usage/next-auth.md
> +1. Pegar a sessão dos cabeçalhos de solicitação usando a função [`getServerSession`](https://next-auth.js.org/configuration/nextjs#getServerSession). A vantagem de usar `getServerSession` em vez do `
```suggestion
1. Pegar a sessão dos headers da request usando a função [`getServerSession`](https://next-auth.js.org/configuration/nextjs#getServerSession). A vantagem de usar `getServerSession` em vez do `getSession` regular é que é uma função que é executada somente do lado do servidor e não faz chamadas de busca desnecessárias. O `create-t3-app` cria uma função auxiliar que abstrai essa API peculiar.
```

2023-02-05 14:10 UTC, Sn0wye commented
> While this is a good edit, I also noticed that the bulletpoint was expanded with some new text in English docs. I'm not sure if we should delete "unstable" in this PR in multiple languages or encourage just plain updating the page itself in these languages in multiple PRs, since it requires a lot of translators at once. Opinions?

Looks great, if the people involved come to an agreement, I'm in.

2023-02-05 14:53 UTC, PiotrekPKP commented on www/src/pages/pl/usage/next-auth.md
> -1. Pobierz sesję z headerów zapytania korzystając z funkcji [`getServerSession`](https://next-auth.js.org/configuration/nextjs#getServerSession). Nie martw się, funkcja ta jest bezpieczna do użycia -
Looks good :+1:

2023-02-05 15:01 UTC, matibox commented on www/src/pages/pl/usage/next-auth.md
> -1. Pobierz sesję z headerów zapytania korzystając z funkcji [`getServerSession`](https://next-auth.js.org/configuration/nextjs#getServerSession). Nie martw się, funkcja ta jest bezpieczna do użycia -
Yup, can confirm that

2023-02-05 16:39 UTC, Sboonny commented on www/src/pages/ar/usage/next-auth.md
> +1. للحصول علي Object الـ Session يمكنك استخدام getServerSession،
LGTM 🎉

![image](https://user-images.githubusercontent.com/88248797/216832145-dbdf2e1d-64e4-412e-82cc-e61ea9e978c4.png)

2023-02-05 21:32 UTC, AmadeusTwi approved these changes
Russian LGTM.

2023-02-05 21:33 UTC, joachimjusth commented on www/src/pages/fr/usage/next-auth.md
> +1. Récupérez la session à partir des en-têtes de requête à l'aide de la fonction [`getServerSession`](https://next-auth.js.org/configuration/nextjs#getServerSession). L'avantage d'utiliser `getServer
Ok for me :)

2023-02-05 21:34 UTC, joachimjusth approved these changes

2023-02-06 05:15 UTC, lodisy approved these changes
👌👌

2023-02-07 22:33 UTC, c-ehrlich approved these changes
Looks good, thanks for updating this :)

> While this is a good edit, I also noticed that the bulletpoint was expanded with some new text in English docs.
I'm not sure if we should delete "unstable" in this PR in multiple languages or encourage just plain updating the page itself in these languages in multiple PRs, since it requires a lot of translators at once.
Opinions?

In this case since it has already been approved for all languages but one let's get it merged. But I agree that in general PRs should not touch multiple languages of docs unless it's just a change to a code block. In the future I'll probably close these and ask for separate PRs to be opened for each language.

2023-02-07 22:33 UTC, merged