feat: Color scheme dropdown
t3-oss/create-t3-app pull request #1230
Opened 2023-02-20 21:37 UTC by AugustinSorel

Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

fixing this issue: https://github.com/t3-oss/create-t3-app/issues/847

This pr changed the old theme toggle to a drop down with 3 options (os default, light and dark)

## Screenshots

![Screenshot from 2023-02-20 21-36-07](https://user-images.githubusercontent.com/48162609/220201810-2fd18c63-0921-4b7f-8e5a-d29ac4cb25d5.png)

💯

2023-02-20 21:43 UTC, juliusmarminge approved these changes
1. Change `Os Default` to `System`
2. The system doesn't actually use the systems theme, you'll need to setup a media listener for that.

2023-02-20 21:44 UTC, juliusmarminge requested changes
(meant to press this xd)

2023-02-20 21:45 UTC, juliusmarminge commented
https://user-images.githubusercontent.com/51714798/220202881-6567e425-6f8c-4977-808b-79c439295e8c.mp4

2023-02-21 03:17 UTC, bai commented on www/src/components/navigation/ColorSchemeSelect.tsx
> +    name: "os default",
```suggestion
    name: "System",
```

To me, `System` sounds more in line with what others do, e.g.:

<img width="499" alt="Screenshot 2023-02-21 at 05 12 04" src="https://user-images.githubusercontent.com/17348/220238720-08bd0d8b-a1cf-48a9-9ead-d2f18c72e6c5.png">

2023-02-23 17:42 UTC, juliusmarminge reviewed
Still some unexpected behaviors:

1. The icon shouldn't change when i change my system preferences, it should be on the system icon as long as i haven't changed it.

2. the button's focus state is triggered when i change the system preferences even though i haven't touched the button

3. If i have changed it, the theme shouldn't change even if i change the system preferences.

demo showcasing these faults:

https://user-images.githubusercontent.com/51714798/220986678-34144c18-060b-4339-8fcd-cdf2ff0565cc.mp4

2023-02-23 17:42 UTC, juliusmarminge commented on www/src/components/navigation/ColorSchemeSelect.tsx
> +  }, []);
this event listener should only run when the system option is selected, we should also have a cleanup function

2023-04-24 05:33 UTC, closed without merging

2023-04-24 05:33 UTC, juliusmarminge commented
Closing as stale so that others don't feel blocked to pick it up