feat: Disable invalid path aliases
t3-oss/create-t3-app pull request #1255
Opened 2023-02-28 23:38 UTC by justasam

Closes #<issue>

## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

- Show error when incorrect path aliases are used
- Do not allow to proceed without entering a correct path alias.

---

## Screenshots

![image](https://user-images.githubusercontent.com/10118845/222007817-3dbf3db3-3eb5-4c85-ad49-d6ed904244fe.png)

💯

2023-03-01 00:08 UTC, juliusmarminge requested changes
Please use the `validate` prop instead of calling the prompter multipel times, see `promptAppName`

2023-03-01 21:03 UTC, c-ehrlich approved these changes
Looks good now. Thanks for the contribution!

2023-03-02 08:12 UTC, justasam commented on cli/src/utils/validateImportAlias.ts
> +  if (input.startsWith(".") || input.startsWith("/")) {
I am not sure I understand -- what do you mean by it follows `/*`? 
AFAIK, the only thing not allowed is import alias starting with `.` or `/` (see [here](https://www.npmjs.com/package/tsconfig-paths)). And for that case regex is overkill - it just makes code harder to read.

2023-03-02 09:53 UTC, juliusmarminge approved these changes

2023-03-02 09:53 UTC, juliusmarminge commented on cli/src/utils/validateImportAlias.ts
> +  if (input.startsWith(".") || input.startsWith("/")) {
Oh ok. I thought they had to have the ending `/*` so for exmple `abc/*` would be valid but just `abc` wouldn't.

> And for that case regex is overkill - it just makes code harder to read.

Totally agree if that's the case!

2023-03-02 10:34 UTC, justasam commented on cli/src/utils/validateImportAlias.ts
> +  if (input.startsWith(".") || input.startsWith("/")) {
Ah, I understand what you've meant. That's handled by `cli/src/helpers/setImportAlias.ts` though, so `abc` will become `abc/` in imports and `abc/*` in tsconfig: 
```TSX
 const normalizedImportAlias = importAlias
    .replace(/\*/g, "") // remove any wildcards (~/* -> ~/)
    .replace(/[^\/]$/, "$&/"); // ensure trailing slash (@ -> ~/)
```

2023-03-03 15:40 UTC, merged