docs(portuguese): updating and adding missing translations
t3-oss/create-t3-app pull request #1372
Opened 2023-04-21 00:40 UTC by fernandohmg

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Updated outdated pages
- Translations improvements and minor fixes

---

2023-04-21 01:09 UTC, Sn0wye requested changes
Just this bit, I'd say mantaining it in English makes more sense.
Besides that, LGTM 🎉

2023-04-21 01:09 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +// `env` é totalmente tipado e fornece autocompletar
```suggestion
// `env` é totalmente tipado e fornece autocomplete
```

2023-04-21 01:21 UTC, fernandohmg commented on www/src/pages/pt/usage/env-variables.mdx
> +// `env` é totalmente tipado e fornece autocompletar
That makes sense! Just added it

2023-04-21 14:51 UTC, Sn0wye approved these changes
Seems nice!

2023-04-24 05:29 UTC, juliusmarminge approved these changes

2023-04-24 05:33 UTC, merged