docs(env-variables): update docs to use T3 Env #1384
t3-oss/create-t3-app pull request #1391
Opened 2023-04-28 23:28 UTC by esau-morais

Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)

---

## Changelog

_Rewrite docs for Environment Variables using T3 Env_

---

💯

2023-04-29 02:36 UTC, esau-morais commented
@juliusmarminge, do you mind checking if the "Validation Logic" section is necessary in the CT3 docs? Maybe we should focus everything related to T3 Env on its own docs.

Also, it's been a while since I've written posts/documentation, so I'd be really grateful to have some critical feedback about my writing

2023-05-02 14:17 UTC, Sn0wye requested changes
Nice writing throughout the whole file, but I'd suggest to maintain the `env.ts` file as `env.mjs`, since it runs before the compilation time, it cannot be Typescript.

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +O Create T3 App usa sua mais nova biblioteca [@t3-oss/env-nextjs](https://env.t3.gg) e [zod](https://zod.dev) para validar variáveis de ambiente durante o tempo de execução (runtime) _e_ buildtime fo
```suggestion
O Create T3 App usa sua mais nova biblioteca [@t3-oss/env-nextjs](https://env.t3.gg) e [zod](https://zod.dev) para validar variáveis de ambiente durante o tempo de execução (runtime) _e_ buildtime fornecendo uma lógica simples no arquivo `src/env.mjs`:
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +## env.ts
```suggestion
## env.mjs
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +_Muito longo, não li; Se você quiser adicionar uma nova variável de ambiente, você deve adicioná-la ao seu `.env` ao definir no validador em `src/env.ts`._
```suggestion
_Muito longo, não li; Se você quiser adicionar uma nova variável de ambiente, você deve adicioná-la ao seu `.env` ao definir no validador em `src/env.mjs`._
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +```ts:env.ts
```suggestion
```ts:env.mjs
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +Quando você quiser usar suas variáveis de ambiente, você pode importá-las de `env.ts` (ou `env.mjs`) e usá-las como faria normalmente. Se você importar isso no cliente e tentar acessar uma variável d
```suggestion
Quando você quiser usar suas variáveis de ambiente, você pode importá-las de `env.mjs` e usá-las como faria normalmente. Se você importar isso no cliente e tentar acessar uma variável de ambiente do lado do servidor, receberá um erro em tempo de execução (runtime).
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +import { env } from "../../env.ts";
```suggestion
import { env } from "../../env.mjs";
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +import { env } from "../env.ts";
```suggestion
import { env } from "../env.mjs";
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +📄 `env.ts`: Adicione a lógica de validação apropriada para as variáveis de ambiente definindo um esquema Zod, por exemplo `TECLA: z.string()`
```suggestion
📄 `env.mjs`: Adicione a lógica de validação apropriada para as variáveis de ambiente definindo um esquema Zod, por exemplo `NOME_DA_VARIAVEL: z.string()`
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +2. Adicione a variável de ambiente a `env.ts`:
```suggestion
2. Adicione a variável de ambiente a `env.mjs`:
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
>  ```ts
```suggestion
```ts:env.mjs
```

2023-05-02 14:17 UTC, Sn0wye commented on www/src/pages/pt/usage/env-variables.mdx
> +    TWITTER_API_TOKEN: z.enum(["development", "test", "production"]),
```suggestion
    TWITTER_API_TOKEN: z.string(),
    NODE_ENV: z.enum(["development", "test", "production"])
```

2023-05-03 19:12 UTC, Sn0wye approved these changes
LGTM 🎉

2023-05-07 07:37 UTC, juliusmarminge requested changes
Looks good - small nits

2023-05-07 07:37 UTC, juliusmarminge commented on www/src/pages/en/usage/env-variables.mdx
> +When you want to use your environment variables, you can import them from the created `env.mjs` (or `env.mjs`) and use them as you would normally do. If you import this on the client and try accessin
Double env.mjs

2023-05-07 07:37 UTC, juliusmarminge commented on www/src/pages/en/usage/env-variables.mdx
> +📄 `env.mjs`: Add the appropriate validation logic for the environment variables by defining a Zod schema inside `createEnv` for each one, e.g. `KEY: z.string()`.
You still need to do destruction in the `runtimeEnv` option

2023-05-07 07:37 UTC, juliusmarminge commented on www/src/pages/en/usage/env-variables.mdx
> -  TWITTER_API_TOKEN: process.env.TWITTER_API_TOKEN,
Put this in runtimeEnv

2023-05-07 11:20 UTC, juliusmarminge approved these changes

2023-05-07 11:20 UTC, merged