docs: update chinese translation
t3-oss/create-t3-app pull request #1453
Opened 2023-05-29 02:05 UTC by AnsonZnl

Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Update faq Chinese document

---

## Screenshots

_[Screenshots]_

💯

2023-05-29 02:15 UTC, fernandoxu commented on www/src/pages/zh-hans/faq.mdx
isMdx: true
---

2023-05-29 02:19 UTC, fernandoxu requested changes
sorry I mean we should sync with [`www/src/pages/en/faq.mdx`](https://github.com/t3-oss/create-t3-app/blob/next/www/src/pages/en/faq.mdx),  you can follow my comments and update the code.

2023-05-29 02:19 UTC, fernandoxu commented on www/src/pages/zh-hans/faq.mdx
isMdx: true
---

2023-05-29 02:19 UTC, fernandoxu commented on www/src/pages/zh-hans/faq.mdx
import Callout from "../../components/docs/callout.tsx";

2023-05-29 02:19 UTC, fernandoxu commented on www/src/pages/zh-hans/faq.mdx
<Callout type="info">
  对于 `/app` 目录中支持的、计划的和正在开发的功能列表,请访问 [beta Next.js
  docs](https://beta.nextjs.org/docs/app-directory-roadmap#supported-and-planned-features).
</Callout>

2023-05-29 02:40 UTC, fernandoxu approved these changes

2023-05-29 12:33 UTC, escwxyz approved these changes

2023-06-02 05:05 UTC, c-ehrlich approved these changes

2023-06-02 18:15 UTC, merged