docs: Update JWT code example to latest codebase
t3-oss/create-t3-app pull request #1511
Opened 2023-07-12 20:03 UTC by ruymon

Closes: #1510 

## ✅ Checklist

- [ x ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ x ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ x ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

Replaced the NextAuth Option code snippet to match the current boilerplate.

---

## Screenshots

N/A

_[Screenshots]_

💯

2023-07-12 22:35 UTC, juliusmarminge requested changes

2023-07-12 22:35 UTC, juliusmarminge commented on www/src/pages/en/usage/next-auth.mdx
> +-     session: ({ session, token }) => ({
user

2023-07-13 00:00 UTC, ruymon commented on www/src/pages/en/usage/next-auth.mdx
> +-     session: ({ session, token }) => ({
My bad 😕

Fixed.

2023-07-13 00:03 UTC, ruymon commented
TBH, this snippet is also in the translated files. I'll also fix that throught the languages before. For now, I'll convert it back to draft.

2023-07-13 00:24 UTC, ruymon commented
Converted to draft was a misclick...

2023-10-25 15:31 UTC, c-ehrlich approved these changes
thanks for the fix :) and sorry for taking forever to get it in

2023-12-03 20:42 UTC, merged