fix: Sanitize project name for WSL compatibility while running start-database.sh
t3-oss/create-t3-app pull request #1991
Opened 2024-10-01 11:56 UTC by aryanp-86

Closes #1928  

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog
- Added sanitizeName function to enforce Docker naming conventions by sanitizing project names.
- Updated dbContainerInstaller to sanitize the parsed project name before writing to the script.
- Modified replacement logic in fs.writeFileSync to use the sanitized project name instead of the placeholder "project1."

---

## Screenshots

_[Screenshots]_

💯

2024-10-03 10:54 UTC, juliusmarminge requested changes

2024-10-03 10:54 UTC, juliusmarminge commented on cli/src/installers/dbContainer.ts
> +}: DbContainerInstallerOptions) => {
what's this type supposed to do? The function is typed as an `Installer` which we iterate over. We expect all installers to have the same signatures so this typing doesn't make much sense

```suggestion
export const dbContainerInstaller: Installer = ({
  projectDir,
  databaseProvider,
  projectName,
}) => {
```

2024-10-03 11:48 UTC, aryanp-86 commented
I have applied the requested changes, including the removal of the unnecessary type. Please review once. PR ready to merge

2024-10-07 20:44 UTC, juliusmarminge approved these changes

2024-10-07 20:44 UTC, merged