feat: use `next.config.ts`
t3-oss/create-t3-app pull request #2000
Opened 2024-10-22 12:09 UTC by ronanru

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

1) Update to Next 15
2) Rename `next.config.js` to `.ts`
3) Rename `env.js` to `.ts`

Todo:
- [ ] Test NextAuth with Next 15

2024-10-22 13:19 UTC, juliusmarminge commented
How useful really is this considering the cjs limitations?

2024-10-22 13:39 UTC, ronanru commented
> How useful really is this (ts config) considering the cjs limitations?

I don't like seeing js files in my src folder. With ts next config `env.js` can be `env.ts`. I don't think it changes anything else.

`next.config.ts` should be more useful in `create-t3-turbo`. I think we can remove `jiti` dependency there, when we update to next 15 there.

2024-10-22 13:41 UTC, juliusmarminge commented
Are you sure this works? t3-env is an ESM only package which is called out to be incompatible ![image](https://github.com/user-attachments/assets/eab4c3c7-0ce4-4c62-ac4c-7a8a4445a83d)

2024-10-22 13:48 UTC, ronanru commented
> Are you sure this works?
I tried multiple configuration, everything seems to work. Dev, Build, LSP all work. I get an error if for env variables are missing.

2024-10-22 15:07 UTC, juliusmarminge commented
Try doing something esm in it, it will crash

This works: 

```ts
// app/env.js
import { createEnv } from "@t3-oss/env-nextjs";
import { vercel } from "@t3-oss/env-nextjs/presets"
import { z } from "zod";

console.log(import.meta.filename)

export const env = createEnv({
  extends: [vercel()],
  server: {
    FOO: z.string()
  },
  experimental__runtimeEnv: {
    FOO: "bar"
  }
});

// next.config.js
import "./app/env.js"

export default {
  /* config options here */
};
```

![CleanShot 2024-10-22 at 17 06 27](https://github.com/user-attachments/assets/7d72a902-c72c-4c2a-80e6-3c6f2ca3e833)

Change file extensions to `.ts`. It crashes:

![CleanShot 2024-10-22 at 17 06 51](https://github.com/user-attachments/assets/0294878e-f783-4f91-8069-d9337520669a)

2024-10-22 15:32 UTC, ronanru commented
oh, ok. I reverted the next config changes. We can add them later when the ESM thing is fixed.

2024-10-22 17:03 UTC, juliusmarminge commented on cli/src/installers/dependencyVersionMap.ts
> +  "next-auth": "beta",
should probably pin this while it's still in beta.

```suggestion
  "next-auth": "5.0.0-beta.25",
```

2024-10-22 17:05 UTC, juliusmarminge commented on cli/template/extras/src/server/auth/base.ts
> +    session: ({ session, user }) => ({
user is not avaialble with jwt session type afaik, or have they changed this in recent versions?

2024-10-22 17:09 UTC, juliusmarminge requested changes
To make sure the auth setup works even if someone has a middleware file, let's use the pattern with separate config and intitialization, os e.g. `src/auth/config.ts` defines the core config and `src/auth/index.ts` inits next auth. also export the auth function wrapped in `React.cache` so it's deduped.

See here for example: https://github.com/juliusmarminge/trellix-trpc/tree/main/src/auth, or https://github.com/t3-oss/create-t3-turbo/tree/main/packages/auth/src

2024-10-22 17:09 UTC, juliusmarminge commented on cli/template/extras/src/server/auth/with-prisma.ts
> -     */
bring back these comments. they are for educational purposes

2024-10-26 11:13 UTC, juliusmarminge approved these changes
I made some more changes to get it more in line with Next Auth v5 standards.

I did some manual testing but would be nice with some more before merging. Can you look it over again @ronanru and make sure my additions are all good?

2024-10-26 13:32 UTC, TheCukitoDev commented
Can @t3dotgg @c-ehrlich and @nexxeln please review the code please?? I think it would be useful to have it implemented already

2024-10-26 14:54 UTC, ronanru commented
Just tested your changes, everything looks good @juliusmarminge

2024-10-26 19:51 UTC, lacymorrow approved these changes
LGTM++

2024-10-26 20:32 UTC, merged