docs: add drizzle docs
t3-oss/create-t3-app pull request #2005
Opened 2024-10-27 16:01 UTC by conlonj25

Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Add docs for Drizzle

---

## Screenshots

![Screenshot 2024-10-27 at 16 57 31](https://github.com/user-attachments/assets/e03eded9-9846-4e52-9f73-0bc0c85ed324)

2024-11-04 08:32 UTC, juliusmarminge requested changes
Great! Just a minor note

2024-11-04 08:32 UTC, juliusmarminge commented on www/src/pages/en/usage/drizzle.md
> +Drizzle is an ORM for TypeScript, that allows you to define your database schema and models in a `schema.ts` file, and then generate a type-safe client that can be used to interact with your database
ther'es no generation step

2024-11-04 08:32 UTC, juliusmarminge commented on www/src/pages/en/usage/drizzle.md
> +The default database is an SQLite database, which is great for development and quickly spinning up a proof-of-concept but is not recommended for production. You can change the database to use by chan
> a proof-of-concept but is not recommended for production

feel like we may need to re-evaluate this now with services like D1 and Turso 😅

2024-11-06 22:09 UTC, conlonj25 commented on www/src/pages/en/usage/drizzle.md
> +Drizzle is an ORM for TypeScript, that allows you to define your database schema and models in a `schema.ts` file, and then generate a type-safe client that can be used to interact with your database
updated

2024-11-06 22:10 UTC, conlonj25 commented on www/src/pages/en/usage/drizzle.md
> +The default database is an SQLite database, which is great for development and quickly spinning up a proof-of-concept but is not recommended for production. You can change the database to use by chan
I rewrote this whole paragraph. It was copied verbatim from the Prisma section and it's not correct.

2025-02-19 17:36 UTC, closed without merging