refactor: inject curried `runPkgManagerInstall` to package installers
t3-oss/create-t3-app pull request #202
Opened 2022-07-16 16:00 UTC by ochicf

# Inject curried `runPkgManagerInstall` to package installers

- [x] I reviewed linter warnings + errors, resolved formatting, types and other issues related to my work
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

I noticed that every installer had to call `runPkgManagerInstall` with a lot of configuration, but IMHO the only configuration they should specify is the `packages` list. So, this MR adds a curryable version of `runPkgManagerInstall` that is curried by `createProject` and injected to every installer as an option. This injected function has been curried with all of the necessary configuration, allowing to clear the call in each installer.

Benefits:
- cleaner code of each installer
- adding new options to `runPkgManagerInstall` will not force adding that parameter in each installer, but instead just once in the `createProject` helper where it's curried
- curried options serve only as defaults, so each installer could still override the options if needed

Another small change added here passing the entirety of the options received in `installPackage` to each package installer, since they share the same shape. This will also prevent from having to pass newly added options here.

2022-07-16 16:02 UTC, ochicf commented
Not sure about the naming convention with currying functions. I've named `curryRunPkgManagerInstall` because it's the most obvious but maybe you prefer something different?

I've also kept the original `runPkgManagerInstall` export, though it's not used outside of that module anymore. Maybe it causes confusion?

2022-07-17 03:16 UTC, nexxeln commented
Oh wow this is much cleaner.

2022-07-17 03:17 UTC, nexxeln approved these changes

2022-07-17 07:51 UTC, juliusmarminge approved these changes
Looks good.

I actually had a draft to remove the `runPackageManagerInstall` entirely and instead add all the packages to package.json and then run a single `npm/pnpm/yarn install` command at the end, but haven't had time to complete it.

2022-07-17 15:09 UTC, ochicf commented on src/installers/prisma.ts
> -    devMode: true,
I missed this, so this is not correct.

2022-07-17 15:09 UTC, ochicf commented on src/installers/tailwind.ts
> -    devMode: true,
Same as previous comment.

2022-07-17 15:14 UTC, ochicf commented
Just noticed in another branch that some installs were actually passing `devMode` and I missed them in the refactor.

2022-07-17 17:59 UTC, juliusmarminge requested changes
Found a typo

2022-07-17 17:59 UTC, juliusmarminge commented on src/utils/runPkgManagerInstall.ts
> +export const curryRunPckgManagerInstall = (
```suggestion
export const curryRunPkgManagerInstall = (
```

2022-07-17 17:59 UTC, juliusmarminge commented on src/utils/runPkgManagerInstall.ts
> +  const curriedRunPckgManagerInstall = async (
```suggestion
  const curriedRunPkgManagerInstall = async (
```

2022-07-17 17:59 UTC, juliusmarminge commented on src/utils/runPkgManagerInstall.ts
> +  return curriedRunPckgManagerInstall;
```suggestion
  return curriedRunPkgManagerInstall;
```

2022-07-17 17:59 UTC, juliusmarminge commented on src/helpers/createProject.ts
> +  const runPkgManagerInstall = curryRunPckgManagerInstall({
```suggestion
  const runPkgManagerInstall = curryRunPkgManagerInstall({
```

2022-07-17 17:59 UTC, juliusmarminge commented on src/helpers/createProject.ts
> +import { curryRunPckgManagerInstall } from "../utils/runPkgManagerInstall.js";
```suggestion
import { curryRunPkgManagerInstall } from "../utils/runPkgManagerInstall.js";
```

2022-07-17 18:30 UTC, ochicf commented
Oh sorry just after I pushed I saw that there was the commit suggestion option 🤦‍♂️ Never saw that before, will use next time.

2022-07-17 18:43 UTC, juliusmarminge approved these changes

2022-07-17 18:43 UTC, merged