docs: language select and outdated docs banner
t3-oss/create-t3-app pull request #780
Opened 2022-11-17 16:09 UTC by juliusmarminge

Closes #770

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

2022-11-17 20:12 UTC, juliusmarminge commented
<img width="841" alt="CleanShot 2022-11-17 at 21 11 15@2x" src="https://user-images.githubusercontent.com/51714798/202549440-2d409390-af02-4984-96d1-4b69cf36f758.png">

needs some more styling and transitions

2022-11-17 21:27 UTC, juliusmarminge commented
@c-ehrlich I'm not sure how we're supposed to show how many revisions behind the English version the page is? Right now just fetching a single commit and comparing their dates.

What would be considered a revision?

2022-11-17 21:29 UTC, juliusmarminge commented
This is how it looks:

<img width="1274" alt="CleanShot 2022-11-17 at 22 28 53@2x" src="https://user-images.githubusercontent.com/51714798/202563560-0b3521b3-3273-49a5-a4b4-a7529cdc2087.png">

2022-11-17 22:08 UTC, juliusmarminge commented
Left todo:

- Animate opening?
- Close when clicking outside

2022-11-18 07:39 UTC, c-ehrlich commented
The header is currently overflowing on mobile

<img width="307" alt="image" src="https://user-images.githubusercontent.com/8353666/202647188-fbab0d6e-237c-479b-ad19-5bb1c890239c.png">

The Vue docs (imo one of the best internationalizations) just uses the language icon without showing which language you're currently on. I think that's ok, the active language is somewhat self evident information (it's either the one you want to read the docs in, or it isn't)
<img width="325" alt="image" src="https://user-images.githubusercontent.com/8353666/202647430-16519810-5b7c-4401-8b09-659b9781f648.png">

Banner looks good from screenshots. Will take a look at the code tonight.

2022-11-18 09:00 UTC, nexxeln commented
> The Vue docs (imo one of the best internationalizations) just uses the language icon without showing which language you're currently on. I think that's ok, the active language is somewhat self evident information (it's either the one you want to read the docs in, or it isn't)
 Yep I agree. It is taking too much space too. Also I don't think we need to generalize the languages with country flags. Just the language name is fine

2022-11-18 09:09 UTC, hodeinavarro commented
Astro also includes a note block when a page is not translated at all, could this be added too?
![image](https://user-images.githubusercontent.com/73967816/202664205-34df8912-d365-4a7b-a51b-74af927c51df.png)

> Note
This page is not available on your language yet, meanwhile you will see the english version. Help us translate! More information about how to contribute.

2022-11-18 10:33 UTC, juliusmarminge commented
> Yep I agree. It is taking too much space too. Also I don't think we need to generalize the languages with country flags. Just the language name is fine

I like flags :( Fair point about the generalization but I still think it adds something

2022-11-19 00:45 UTC, juliusmarminge commented
We should probably have some fallback behavior if the files doesn't exist yet for a specific langauge right?

https://user-images.githubusercontent.com/51714798/202825138-10f76736-6c8f-4a08-a0e3-18bcf45fe1fe.mp4

Example: Astro renders the english version in the sidebar if it doesn't exist for the native language:

<img width="243" alt="CleanShot 2022-11-19 at 01 44 56@2x" src="https://user-images.githubusercontent.com/51714798/202825229-cb65c5c7-832d-4b1a-bb2c-87a0d91e0f88.png">

2022-11-19 00:46 UTC, juliusmarminge commented on www/src/pages/sv/installation.md
> +---
NOTE: These files should be removed before merging

2022-11-19 17:27 UTC, c-ehrlich commented on www/src/components/docs/outdatedDocsBanner.astro
> +        older than the English version, and might be outdated. If you're a
could this take a `language: KnownLanguage` prop (or some other way to know what the active language is) and then render the message in that language, with a fallback to English?

2022-11-19 17:27 UTC, c-ehrlich commented on www/src/components/docs/outdatedDocsBanner.astro
> +        older than the English version, and might be outdated. If you're a
oh probably just `const [_1, _2, lang] = path.split("/");`

2022-11-21 06:45 UTC, AyanavaKarmakar requested changes

2022-11-21 06:45 UTC, AyanavaKarmakar commented on www/src/components/docs/outdatedDocsBanner.astro
> +          to go to the English version
```suggestion
          go to the English version
```

2022-11-21 06:45 UTC, AyanavaKarmakar commented on www/src/components/docs/outdatedDocsBanner.astro
> +        older than the English version, and might be outdated. If you're a
```suggestion
        older than the English version and might be outdated. If you're a
```

2022-11-21 06:46 UTC, AyanavaKarmakar commented on www/src/components/docs/outdatedDocsBanner.astro
> +        native speaker of this language, and would like to contribute to the
```suggestion
        native speaker of this language and would like to contribute to the
```

2022-11-23 20:25 UTC, juliusmarminge commented on www/src/components/docs/outdatedDocsBanner.astro
> +          to go to the English version
```suggestion
        view the English version
```

2022-11-23 20:52 UTC, c-ehrlich requested changes
remove the nonexistent test languages and we're ready to merge :)

2022-11-23 20:54 UTC, c-ehrlich approved these changes
💯

2022-11-23 20:55 UTC, merged