feat: left sidebar language
t3-oss/create-t3-app pull request #820
Opened 2022-11-21 11:43 UTC by c-ehrlich

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Some more preparations for getting translations online

Uses the active language in the left sidebar and shows the table of contents for that language. Also makes the links in the sidebar link to pages of that language (manually for now, maybe there is an elegant way to this automatic...)

Tested this on @Yevhenii-Bakhmat 's RU branch (forgot to take screenshot, so made a new screenshot with a fake translated page), but should work on any translation branch/language.

Translators will also need to update the sidebar in their language in `www/src/config.ts`, for the in progress translations I put a note about this in the first list item.

---

## Screenshots

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8353666/203042091-26831b56-2a9a-4e4e-8530-9bce564b8e82.png">

💯

2022-11-21 11:45 UTC, juliusmarminge commented
Could have just continued on my PR :(

2022-11-21 11:48 UTC, c-ehrlich commented
> Could have just continued on my PR :(

oh yeah my bad :/

feel free to merge this into your pr and close

2022-11-21 11:48 UTC, Yevhenii-Bakhmat commented
I think parsing a titles from tanslation pages would be better then using constant with paths and labels

2022-11-21 12:06 UTC, c-ehrlich commented
> I think parsing a titles from tanslation pages would be better then using constant with paths and labels

i agree this would be better, but can't think of an easy way to do it currently. only way i can think of is to import every article in each language in config.ts and get frontmatter from all of them, which is a lot. maybe there's something to help us in astro docs, can check tonight.

2022-11-23 20:32 UTC, juliusmarminge commented on www/src/components/navigation/leftSidebar.astro
> +                        isActive && "border-t3-purple-300/20",
prob missed an `!` here? both entries are `isActive` now

2022-11-23 22:21 UTC, c-ehrlich commented on www/src/components/navigation/leftSidebar.astro
> +                        isActive && "border-t3-purple-300/20",
yup, fixed now

2022-11-24 21:43 UTC, juliusmarminge commented
What's the status here?

2022-11-24 23:45 UTC, c-ehrlich commented
> What's the status here?

Need to resolve conflicts tomorrow, other than that ready to review/merge.

2022-11-25 19:08 UTC, c-ehrlich commented
ready for review now @juliusmarminge

2022-11-27 12:22 UTC, juliusmarminge commented
too disappears https://share.cleanshot.com/502Vvd

2022-11-27 12:24 UTC, juliusmarminge commented
This banner also looks a bit weird, but honestly im not sure how it should look so can't say 
<img width="862" alt="CleanShot 2022-11-27 at 13 23 57@2x" src="https://user-images.githubusercontent.com/51714798/204135025-fa588cf3-f792-4c4f-a5ee-ee4e9d11f6bc.png">

2022-11-27 23:14 UTC, c-ehrlich commented
> This banner also looks a bit weird, but honestly im not sure how it should look so can't say <img alt="CleanShot 2022-11-27 at 13 23 57@2x" width="862" src="https://user-images.githubusercontent.com/51714798/204135025-fa588cf3-f792-4c4f-a5ee-ee4e9d11f6bc.png">

There are two options for this
1. Always display it in English, then it should be ltr
2. Translate this banner for other languages (seems to make sense), then it should be rtl as it is now.
if we decide to start translating not just .md files, we'll probably want https://www.npmjs.com/package/astro-i18next

Re: ToC - will check what's going on tomorrow

2022-11-28 09:28 UTC, juliusmarminge commented
> Always display it in English, then it should be ltr

This for now maybe? Can always change later

2022-11-28 20:54 UTC, c-ehrlich commented
<img width="420" alt="image" src="https://user-images.githubusercontent.com/8353666/204378700-a7c49e20-371b-4899-969f-c96693680139.png">
something weird going on with the external link icons in rtl

2022-11-28 21:47 UTC, c-ehrlich commented
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8353666/204387957-43a93e65-8eaa-4c03-b787-c8ac07437600.png">

2022-11-28 22:58 UTC, c-ehrlich commented
also dont merge before arabic is removed from the list of known languages, otherwise we're deploying two fake arabic pages

2022-11-29 23:06 UTC, juliusmarminge commented on cli/package.json
> +    "prettier-plugin-tailwindcss": "^0.2.0",
i wanted to use satisfies but didn't work.

upgraded these to get the parsing correct

2022-11-30 20:21 UTC, c-ehrlich commented
@julius lmk when you're ready to merge and i'll remove the arabic placeholder stuff (or feel free to remove it yourself)

2022-11-30 23:26 UTC, juliusmarminge requested changes

2022-11-30 23:26 UTC, juliusmarminge commented on .changeset/heavy-buckets-try.md
> +upgrade prettier and eslint (for docs)
rm this.

we're not updating any cli logic or files for the scaffolded app, so a publish here won't do anything. it's just devDeps being updated

2022-12-01 19:21 UTC, juliusmarminge approved these changes
cool lets ship

2022-12-02 00:30 UTC, merged