feat: add blank target to base template
t3-oss/create-t3-app pull request #917
Opened 2022-12-04 09:48 UTC by sharkby7e

Closes #<issue>

## ✅ Checklist

- [ ✅ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ ✅ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ✅ ] I performed a functional test on my final commit

---

## Changelog

Links on index page in template open in new tabs 🚀

💯

2022-12-04 09:59 UTC, c-ehrlich requested changes
Thanks for the PR, I agree that it's better this way. Could you also change it in the other index versions in the page-studs folder?

2022-12-05 19:15 UTC, c-ehrlich approved these changes
thanks :)

2022-12-05 19:18 UTC, c-ehrlich requested changes
Just realized the [changeset](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md#when-youre-done) is missing. Add that and we can merge.

2022-12-05 21:05 UTC, juliusmarminge approved these changes

2022-12-05 22:28 UTC, c-ehrlich approved these changes

2022-12-05 22:29 UTC, merged