docs(AR): new folder structure Arabic
t3-oss/create-t3-app pull request #988
Opened 2022-12-17 19:21 UTC by Sboonny

Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Changed the file to `.mjx`
- Fixed heading structure.
- Removed ملف and مجلد from the heading because some were misused and describing the wrong state of the folder/file.

---

## Screenshots

_[Screenshots]_

💯

2022-12-17 19:25 UTC, Sboonny reviewed
Random question about the original structure of the page

2022-12-17 19:25 UTC, Sboonny commented on www/src/pages/ar/folder-structure.mdx
> +### `.env`
Random question, should this be heading two? `##`

I think the heading is used here to indicate where the file is, so if it's heading 2, then it's in the root section of the app.

2022-12-17 19:25 UTC, Sboonny commented on www/src/pages/ar/folder-structure.mdx
> +### `.env.example`
Same, and the sections below it

2022-12-17 23:14 UTC, juliusmarminge commented
> Random question about the original structure of the page

I think we did this to make the sizing more appropriate cause there were some overflow when we followed the "actual proper heading numbers" so to say...

2022-12-17 23:15 UTC, juliusmarminge requested changes
I think all the `sub` ones should go since now you pick your selections in the Form component

2022-12-18 14:05 UTC, juliusmarminge approved these changes

2022-12-18 14:05 UTC, merged